apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: repo-1112116189
  namespace: argocd
spec:
  encryptedData:
    project: AgAtz5dAHiY2il98wtJBECqfSv69D6Z36jjvJZGLVBPFtPKeyGl7+Lu1+AlSPMSn6iUtymY+2XQgjIieoHm9E882BzMNanvDyyPRdaNpxmUBDNNdm3UL1sEDYaASMxJCkhBqm1y4HA/hQEeW6Itv8eNDBagKFR+XhQrtESfH1LFE8ojVKEpz2VZinIeeYoPThA9RNEvD1ZpBHDVF8XXGNt6uenIPPFJ1y5KoOR9+10B08ON8pkmDrtLQdej8p34Tda9iQURE+LCzfpgHur8DsvzFbYzjCVSX2EeS8cN9olf7YdR3IjFw5NKZYByZp/peN7lWyGbarX+eg2gF/Z7/G8eRVA+f3aSXrshz3Ycfaz93I22KYPDIsl/QwaZjs3m8FDcqs3UZTQsN77UGoRdh67VbGfG/xTpQUl3Z4/EBBrkuQRB46Kgyd4AgJNN/gZisIt+VWJHzPZnhg0IMyytIps25Etg02vQgrWZ550F2gwIikvMj9hm5zONmpAQX8W7+mGgiaFv6Pmscx4ALdaYLrEcCze+x0imiZ5mkwcTIEAV4PLRkKcBAYzU2kFCuMutQFJUNo2Jla210WT/aCFbx2ybXJtY2ckB4JrvKOKUt8p761nP4wmYkxz/dQbCQbZ9J0B+G+DUtgBbVoEoT0jI4lZYcVmyiEeA8DW70TXrS36S2mMPS1krLeMwQ5dnDwEKTmKZG48DtRWbU
    type: AgBd2212hZQ0YN7fUppQSsDMqwEhIN4mMtepQbTSYewug6JCcSULQ8YaLEehe4KipCp/do10DVtXL6s4QWFLSraGbEoS2zQSRg9l9Cz+H732/7S1rjOC9PrTA7e1ywYUB2PpYTSjq79o34lIYFLWBitXuiP05pAOXVEkPLtBCY8BcAVdju7vqFJw2g7lR5b/yGa7H4L2lgKLODHIlU45S8HYLWnhlAjLJS6IQI5ue2w7IocmVkr7qsQWYaoF4O6OYehr6iIW6ywlBDoSkHxKP88BotoZV7Tlpco25g/6d88Cdkv6PGM49De9K49oE/XilDtBJtv8YkwVoXg0/W6fYZRojUmrv+AbtStTThOgm4aKhmTPNmjxSCRiNkUU0AaS7KhQC5IF4+ZJFlV3IKQ8V453reHguBL0VgomNur/br8BOpBuWRRy76ncH0rsk22aLlcz3NvZrrWdSlsC7xRq18wpSSAkyJYNh6+CgFsXKI/ZvwJJicj5RWYkmCCEfVet/rUtGBO89JNZNbdNfzczRIOlwFyAKJq9xPVfRcSkcT4VILzKPCpzoRMmMTYq4CaF88N4hAkKzzCZLp4rw57+gzedlqlwycac62xasjk4/Tpp1s+oH+DCejONTbCOCjgU0aU6MI7cEKWkS6g3kaW+pByaRRceF1/9H+ZYGfO8/Xqt8z/1n2cMXSAi7hImcQz+kMGWxH0=
    url: AgB70FZqIXV9Xrb7kMstqlfohtVgXpyJm5nfiPhwg3j0AY37o3FEsqeftjq6zxu9hr0BODB95XQR+5EXEIFS21mJrpWK/ww2SES/JUzDqs3Eox8WvLGRxt92IBw/wxCM86B1WahMAhkjuIglLdcf1L8l+BWbAspN1XuYerPysQhV/rBqILGpCeU7Wy+cF3irbpwFy1zYUZ/5OOFJFUejLClyuGaW4tyxbR42jz0FrRRRMOXDY06DRhrZVcKjlojEX6ViBWFt8TtfSakeA0acUurFRTNAyFinuAsAKLw8LQiciM3mBGhk/zC3OLdefx2CM5VyKaE5P4FL3ydjfdoaO8kXjlk0lQgaeYXgCX3/inGag2esHcrumVVaY8YKetRWMzWznp+6VVL5dLJhaJsK8yLPIcwvpW57MpeJKCg7N0rhII84PzZNGJIkJi/vxuQPbEvo08WXtJop17HsxBqWjp5ecTv+rKOtXH58n2AVssA7koY7ip+S7WFJ4ub7gUyjUWj37z9nMsVYp/6gS2/xZQjQALmZX7rA4E6wbRX6Tbd860le5Z/jJxqxIVycC02apVHusDze9qp98JedIphT/GHv8gesO0ZrtFWOJr/IYMkAC5ZrJCl987d1xeuaUo7PsTw6Jv9l0hbMNsefaFmMRfyblMz3tSbvmY0HSdlxn6s6pnE9ozPa1JCqm/jzN8c7yZsonMbD1e019vlyYrnT5YS/Fp4FQxl++QIiKw9oQPnALkNGhHpiLCqN
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: repo-1112116189
      namespace: argocd
    type: Opaque

